import React from 'react';

// Ensure these classes are generated by Tailwind
// bg-green-500 text-green-500 border-green-500
// bg-blue-500 text-blue-500 border-blue-500
// bg-purple-500 text-purple-500 border-purple-500
// bg-red-500 text-red-500 border-red-500
// bg-orange-500 text-orange-500 border-orange-500
// bg-yellow-500 text-yellow-500 border-yellow-500

const AlertTypes = () => {
  return (
    <div className="flex flex-col gap-7 items-start w-full">
      <div className="flex flex-col gap-2.5 items-start w-full">
        <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
          <span className="text-black text-lg tracking-[0.005em] font-medium">
            Types
          </span>
        </p>
        <div className="w-full h-px bg-gray-200"></div>
      </div>
      <div className="flex gap-9 items-start">
        <div className="flex flex-col gap-[15px] items-start">
          <div className="relative w-full h-[17px]">
            <p className="text-sm leading-[18px] tracking-[0.005em] text-slate-600">
              <span className="text-slate-600 text-sm tracking-[0.005em] font-medium">
                Solid
              </span>
            </p>
          </div>
          <div className="flex items-start w-full">
            <div className="rounded-md p-4 flex gap-5 items-start flex-1 w-full bg-primary">
              <div className="flex flex-col gap-[5px] items-start flex-1 w-full">
                <div className="pr-[35px] flex gap-2.5 items-start w-full">
                  <p className="text-lg leading-[22px] tracking-[0.005em] text-white">
                    <span className="text-white text-lg tracking-[0.005em] font-bold">
                      Solid Purple Alert
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col gap-[15px] items-start">
          <div className="relative w-full h-[17px]">
            <p className="text-sm leading-[18px] tracking-[0.005em] text-slate-600">
              <span className="text-slate-600 text-sm tracking-[0.005em] font-medium">
                Soft
              </span>
            </p>
          </div>
          <div className="flex items-start w-full">
            <div className="rounded-md p-4 flex gap-5 items-start flex-1 w-full bg-primary-light">
              <div className="flex flex-col gap-[5px] items-start flex-1 w-full">
                <div className="pr-[35px] flex gap-2.5 items-start w-full">
                  <p className="text-lg leading-[22px] tracking-[0.005em] text-neutral-text">
                    <span className="text-neutral-text text-lg tracking-[0.005em] font-bold">
                      Soft Purple Alert
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col gap-[15px] items-start">
          <div className="relative w-full h-[17px]">
            <p className="text-sm leading-[18px] tracking-[0.005em] text-slate-600">
              <span className="text-slate-600 text-sm tracking-[0.005em] font-medium">
                White
              </span>
            </p>
          </div>
          <div className="flex items-start w-full">
            <div className="rounded-md border border-gray-200 px-6 py-4 flex gap-5 items-start flex-1 w-full bg-white">
              <div className="flex flex-col gap-[5px] items-start flex-1 w-full">
                <div className="pr-[35px] flex gap-2.5 items-start w-full">
                  <p className="text-lg leading-[22px] tracking-[0.005em] text-neutral-text">
                    <span className="text-neutral-text text-lg tracking-[0.005em] font-bold">
                      White Alert
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-[15px] items-start">
        <div className="relative w-full h-[17px]">
          <p className="text-sm leading-[18px] tracking-[0.005em] text-slate-600">
            <span className="text-slate-600 text-sm tracking-[0.005em] font-medium">
              Info
            </span>
          </p>
        </div>
        <div className="flex items-start w-full">
          <div className="rounded-md p-2 text-sm flex gap-5 items-start flex-1 w-full bg-primary">
            <div className="flex flex-col gap-[5px] items-start flex-1 w-full">
              <div className="pr-[35px] flex gap-2.5 items-start w-full">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-white">
                  <span className="text-white text-lg tracking-[0.005em] font-bold">
                    Info Alert
                  </span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AlertTypes; 