export enum SocketAction {
  UPDATE_APPEARANCE = 'UPDATE_APPEARANCE',
  UPDATE_IDEA = 'UPDATE_IDEA',
  UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
  UPDATE_ROADMAP = 'UPDATE_ROADMAP',
  UPDATE_TAG = 'UPDATE_TAG',
  UPDATE_WIDGET = 'UPDATE_WIDGET',
}
