import { useState } from 'react';
import TabNavigation from '../TabNavigation';
import AlertTypes from '../../components/ui/alert/AlertTypes';
import AlertShapes from '../../components/ui/alert/AlertShapes';
import AlertSolid from '../../components/ui/alert/AlertSolid';
import AlertSoft from '../../components/ui/alert/AlertSoft';
import AlertDescription from '../../components/ui/alert/AlertDescription';
import AlertExamples from '../../components/ui/alert/AlertExamples';
import { AvatarComponent } from '../../components/ui/avatar';
import AccordionBasic from '../ui/accordion/AccordionBasic';
import AccordionBordered from '../ui/accordion/AccordionBordered';
import AccordionLightBackground from '../ui/accordion/AccordionLightBackground';
import AccordionDivider from '../ui/accordion/AccordionDivider';
import AccordionNested from '../ui/accordion/AccordionNested';
import BadgeComponent from '../ui/badge/BadgeComponent';
import ColorDisplay from '../ui/ColorDisplay';
import ButtonDisplay from '../ui/ButtonDisplay';

// Ensure these classes are generated by Tailwind
// Interdimensional Blue
// bg-interdimensional-blue-10 bg-interdimensional-blue-50 bg-interdimensional-blue-100
// bg-interdimensional-blue-200 bg-interdimensional-blue-300 bg-interdimensional-blue-400
// bg-interdimensional-blue-500 bg-interdimensional-blue-600 bg-interdimensional-blue-700

// Portland Orange
// bg-portland-orange-100 bg-portland-orange-200 bg-portland-orange-300
// bg-portland-orange-400 bg-portland-orange-500 bg-portland-orange-600
// bg-portland-orange-700

// Topaz
// bg-topaz-100 bg-topaz-200 bg-topaz-300 bg-topaz-400 bg-topaz-500
// bg-topaz-600 bg-topaz-700

// Cetacean Blue
// bg-cetacean-blue-100 bg-cetacean-blue-200 bg-cetacean-blue-300
// bg-cetacean-blue-400 bg-cetacean-blue-500

// Ghost White
// bg-ghost-white-400

// Slate
// bg-slate-50 bg-slate-100 bg-slate-200 bg-slate-300 bg-slate-400
// bg-slate-500 bg-slate-600 bg-slate-700 bg-slate-800 bg-slate-900

// Gray
// bg-gray-50 bg-gray-100 bg-gray-200 bg-gray-300 bg-gray-400
// bg-gray-500 bg-gray-600 bg-gray-700 bg-gray-800 bg-gray-900

// Zinc
// bg-zinc-50 bg-zinc-100 bg-zinc-200 bg-zinc-300 bg-zinc-400
// bg-zinc-500 bg-zinc-600 bg-zinc-700 bg-zinc-800 bg-zinc-900

// Emerald
// bg-emerald-50 bg-emerald-100 bg-emerald-200 bg-emerald-300 bg-emerald-400
// bg-emerald-500 bg-emerald-600 bg-emerald-700 bg-emerald-800 bg-emerald-900

// Cyan
// bg-cyan-50 bg-cyan-100 bg-cyan-200 bg-cyan-300 bg-cyan-400
// bg-cyan-500 bg-cyan-600 bg-cyan-700 bg-cyan-800 bg-cyan-900

// Sky
// bg-sky-50 bg-sky-100 bg-sky-200 bg-sky-300 bg-sky-400
// bg-sky-500 bg-sky-600 bg-sky-700 bg-sky-800 bg-sky-900

// Blue
// bg-blue-50 bg-blue-100 bg-blue-200 bg-blue-300 bg-blue-400
// bg-blue-500 bg-blue-600 bg-blue-700 bg-blue-800 bg-blue-900

// Purple
// bg-purple-50 bg-purple-100 bg-purple-200 bg-purple-300 bg-purple-400
// bg-purple-500 bg-purple-600 bg-purple-700 bg-purple-800 bg-purple-900

// Rose
// bg-rose-50 bg-rose-100 bg-rose-200 bg-rose-300 bg-rose-400
// bg-rose-500 bg-rose-600 bg-rose-700 bg-rose-800 bg-rose-900

// Orange
// bg-orange-50 bg-orange-100 bg-orange-200 bg-orange-300 bg-orange-400
// bg-orange-500 bg-orange-600 bg-orange-700 bg-orange-800 bg-orange-900

// Button Colors
// bg-button-dark bg-button-gray bg-emerald-500 bg-blue-500
// bg-button-purple bg-red-500 bg-button-orange bg-yellow-500
// bg-white text-gray-600
// border-button-dark border-button-gray border-emerald-500 border-blue-500
// border-button-purple border-red-500 border-button-orange border-yellow-500
// border-white
// text-button-dark text-button-gray text-emerald-500 text-blue-500
// text-button-purple text-red-500 text-button-orange text-yellow-500
// text-white
// bg-gray-100 bg-gray-50 bg-emerald-100 bg-blue-50 bg-red-100 bg-yellow-100
// bg-white/10

// Purple Button Variants
// bg-purple-50 bg-purple-100 bg-purple-200 bg-purple-300 bg-purple-400
// bg-purple-500 bg-purple-600 bg-purple-700 bg-purple-800 bg-purple-900

// Solid Button Colors
// bg-button-dark bg-button-gray bg-emerald-500 bg-blue-500
// bg-button-purple bg-red-500 bg-button-orange bg-yellow-500
// bg-white text-gray-600

// Outlined Button Borders
// border-button-dark border-button-gray border-emerald-500 border-blue-500
// border-button-purple border-red-500 border-button-orange border-yellow-500
// border-white

// Ghost Button Text Colors
// text-button-dark text-button-gray text-emerald-500 text-blue-500
// text-button-purple text-red-500 text-button-orange text-yellow-500
// text-white

// Soft Button Backgrounds
// bg-gray-100 bg-gray-50 bg-emerald-100 bg-blue-50 bg-ebdff9
// bg-red-100 bg-ffd8cc bg-yellow-100 bg-white/10

// Soft Button Text Colors
// text-gray-900 text-gray-700 text-emerald-500 text-blue-500
// text-purple-700 text-red-500 text-orange-700 text-yellow-500
// text-white

// Block Button Styles
// bg-[#5a00cd] text-white
// shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] border-gray-200
// bg-white text-[#09041a]

// Example Button Styles
// shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] border-gray-200
// bg-white text-[#09041a] bg-[#5a00cd] text-white
// rounded-md border-[#e1e0e5] text-[#110733]

// const fontFamilies = ['sans', 'serif', 'mono'];
// const fontSizes = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl', '7xl', '8xl', '9xl'];
// const fontWeights = ['normal', 'medium', 'bold'];

const DesignPage = () => {
  const [activeTab, setActiveTab] = useState<{ id: string; text: string }>({
    id: 'accordion',
    text: 'Accordion',
  });

  const handleTabChange = (tab: { id: string; text: string }) => {
    setActiveTab(tab);
  };

  const colorGroups = [
    {
      name: 'Interdimensional Blue',
      shades: ['10', '50', '100', '200', '300', '400', '500', '600', '700'],
    },
    {
      name: 'Portland Orange',
      shades: ['100', '200', '300', '400', '500', '600', '700'],
    },
    {
      name: 'Topaz',
      shades: ['100', '200', '300', '400', '500', '600', '700'],
    },
    {
      name: 'Cetacean Blue',
      shades: ['100', '200', '300', '400', '500'],
    },
    {
      name: 'Ghost White',
      shades: ['400'],
    },
    {
      name: 'Slate',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Gray',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Zinc',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Emerald',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Cyan',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Sky',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Blue',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Purple',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Rose',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
    {
      name: 'Orange',
      shades: [
        '50',
        '100',
        '200',
        '300',
        '400',
        '500',
        '600',
        '700',
        '800',
        '900',
      ],
    },
  ];

  const tabs = [
    { id: 'accordion', text: 'Accordion' },
    { id: 'alerts', text: 'Alerts' },
    { id: 'avatar', text: 'Avatar' },
    { id: 'badges', text: 'Badges' },
    { id: 'colors', text: 'Colors' },
    { id: 'buttons', text: 'Buttons' },
    { id: 'fonts', text: 'Fonts' },
  ];

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <h1 className="text-2xl font-bold mb-12">Design System</h1>
      <TabNavigation
        activeTab={activeTab}
        onTabChange={handleTabChange}
        tabs={tabs}
      />
      <div className="mt-6">
        {activeTab.id === 'accordion' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Accordion</h2>
            <div className="flex flex-col gap-9 items-start relative">
              <AccordionBasic />
              <AccordionBordered />
              <AccordionLightBackground />
              <AccordionDivider />
              <AccordionNested />
            </div>
          </section>
        )}
        {activeTab.id === 'alerts' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Alerts</h2>
            <AlertTypes />
            <AlertShapes />
            <AlertSolid />
            <AlertSoft />
            <AlertDescription />
            <AlertExamples />
          </section>
        )}
        {activeTab.id === 'avatar' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Avatar</h2>
            <div className="flex flex-wrap gap-[30px] items-start relative max-w-[1280px] mx-auto">
              <div className="flex flex-col gap-2.5 items-start relative w-full">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Types
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex flex-wrap gap-9 items-start relative">
                <div className="flex flex-col gap-[15px] items-start relative">
                  <div className="relative w-full h-[17px] bg-transparent">
                    <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600">
                      <span className="text-slate-600 text-[15px] tracking-[0.005em] font-medium">
                        Do Not Disturb
                      </span>
                    </p>
                  </div>
                  <div className="flex gap-5 items-start relative">
                    <AvatarComponent text="A" status="dnd" />
                    <AvatarComponent
                      src="https://picsum.photos/id/38/46/46"
                      status="dnd"
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2.5 items-start relative w-full">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Icon
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex flex-wrap gap-[50px] items-start relative">
                <div className="flex flex-col gap-[15px] items-start relative">
                  <div className="relative w-full h-[17px] bg-transparent">
                    <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600">
                      <span className="text-slate-600 text-[15px] tracking-[0.005em] font-medium">
                        Icon
                      </span>
                    </p>
                  </div>
                  <div className="flex gap-5 items-start relative">
                    <AvatarComponent text="A" />
                    <AvatarComponent src="https://picsum.photos/id/52/46/46" />
                  </div>
                </div>
              </div>
            </div>
          </section>
        )}
        {activeTab.id === 'badges' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Badges</h2>
            <div className="flex flex-col gap-[30px] items-start self-stretch relative w-full">
              <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Types
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex gap-9 items-start relative">
                <BadgeComponent type="white" text="Badge" />
                <BadgeComponent type="outlined" text="Badge" />
                <BadgeComponent type="soft" text="Badge" />
                <BadgeComponent type="solid" text="Badge" />
              </div>
              <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full mt-6">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Sizes
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex gap-9 items-start relative">
                <BadgeComponent type="soft" text="Badge-sm" size="sm" />
                <BadgeComponent type="soft" text="Badge" size="md" />
                <BadgeComponent type="soft" text="Badge-lg" size="lg" />
              </div>
              <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full mt-6">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Shapes
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex gap-9 items-start relative">
                <BadgeComponent type="soft" text="Badge" shape="rounded" />
                <BadgeComponent type="soft" text="Badge" shape="pilled" />
              </div>
              <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full mt-6">
                <p className="text-lg leading-[22px] tracking-[0.005em] text-black">
                  <span className="text-black text-lg tracking-[0.005em] font-medium">
                    Outlined
                  </span>
                </p>
                <div className="w-full h-px bg-gray-200"></div>
              </div>
              <div className="flex flex-row gap-9 items-start relative">
                <div className="flex flex-col gap-[15px] items-start relative w-[150px]">
                  <BadgeComponent type="outlined" text="Badge" color="gray" />
                  <BadgeComponent
                    type="outlined"
                    text="Badge"
                    color="gray-light"
                  />
                  <BadgeComponent
                    type="outlined"
                    text="Badge"
                    color="emerald"
                  />
                  <BadgeComponent type="outlined" text="Badge" color="blue" />
                  <BadgeComponent type="outlined" text="Badge" color="purple" />
                  <BadgeComponent type="outlined" text="Badge" color="red" />
                  <BadgeComponent type="outlined" text="Badge" color="orange" />
                  <BadgeComponent type="outlined" text="Badge" color="yellow" />
                  <BadgeComponent type="outlined" text="Badge" color="white" />
                </div>
                <div className="flex flex-col gap-[15px] items-start relative w-[150px]">
                  <BadgeComponent type="soft" text="Badge" color="gray" />
                  <BadgeComponent type="soft" text="Badge" color="gray-light" />
                  <BadgeComponent type="soft" text="Badge" color="emerald" />
                  <BadgeComponent type="soft" text="Badge" color="blue" />
                  <BadgeComponent type="soft" text="Badge" color="purple" />
                  <BadgeComponent type="soft" text="Badge" color="red" />
                  <BadgeComponent type="soft" text="Badge" color="orange" />
                  <BadgeComponent type="soft" text="Badge" color="yellow" />
                  <BadgeComponent type="soft" text="Badge" color="white" />
                </div>
                <div className="flex flex-col gap-[15px] items-start relative w-[150px]">
                  <BadgeComponent type="solid" text="Badge" color="gray" />
                  <BadgeComponent
                    type="solid"
                    text="Badge"
                    color="gray-light"
                  />
                  <BadgeComponent type="solid" text="Badge" color="emerald" />
                  <BadgeComponent type="solid" text="Badge" color="blue" />
                  <BadgeComponent type="solid" text="Badge" color="purple" />
                  <BadgeComponent type="solid" text="Badge" color="red" />
                  <BadgeComponent type="solid" text="Badge" color="orange" />
                  <BadgeComponent type="solid" text="Badge" color="yellow" />
                  <BadgeComponent type="solid" text="Badge" color="white" />
                </div>
              </div>
            </div>
          </section>
        )}
        {activeTab.id === 'colors' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Colors</h2>
            {colorGroups.map((group) => (
              <div key={group.name} className="mb-8">
                <h3 className="text-md font-semibold mb-4">{group.name}</h3>
                <div className="grid grid-cols-9 gap-4">
                  {group.shades.map((shade) => {
                    const className = `bg-${group.name.toLowerCase().replace(' ', '-')}-${shade}`;
                    console.log(`Applying class: ${className}`);
                    return (
                      <ColorDisplay
                        key={shade}
                        name={shade}
                        className={className}
                      />
                    );
                  })}
                </div>
              </div>
            ))}
          </section>
        )}
        {activeTab.id === 'buttons' && (
          <section className="mb-12">
            <h2 className="text-lg font-semibold mb-6">Buttons</h2>
            <div className="flex flex-col gap-10">
              <div className="flex flex-col gap-4">
                <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                  Shapes
                </p>
                <div className="flex gap-4">
                  <ButtonDisplay type="solid" label="Rounded" shape="rounded" />
                  <ButtonDisplay type="solid" label="Pilled" shape="pilled" />
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                  Types
                </p>
                <div className="flex gap-4">
                  <ButtonDisplay type="solid" label="Solid" />
                  <ButtonDisplay type="outline" label="Outline" />
                  <ButtonDisplay type="ghost" label="Ghost" />
                  <ButtonDisplay type="soft" label="Soft" />
                  <ButtonDisplay type="link" label="Link" />
                  <ButtonDisplay type="default" label="Default" />
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                  States
                </p>
                <div className="flex gap-4">
                  <ButtonDisplay type="solid" label="Default" state="default" />
                  <ButtonDisplay type="solid" label="Hover" state="hover" />
                  <ButtonDisplay type="solid" label="Focus" state="focus" />
                  <ButtonDisplay
                    type="solid"
                    label="Disabled"
                    state="disabled"
                  />
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                  Sizes
                </p>
                <div className="flex gap-4">
                  <ButtonDisplay type="solid" label="Small" />
                  <ButtonDisplay type="solid" label="Default" />
                  <ButtonDisplay type="solid" label="Large" />
                </div>
              </div>
              <div className="flex gap-10">
                <div className="flex flex-col gap-[15px] items-start">
                  <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                    Solid
                  </p>
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="button-dark"
                  />
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="button-gray"
                  />
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="emerald-500"
                  />
                  <ButtonDisplay type="solid" label="Button" color="blue-500" />
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="button-purple"
                  />
                  <ButtonDisplay type="solid" label="Button" color="red-500" />
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="button-orange"
                  />
                  <ButtonDisplay
                    type="solid"
                    label="Button"
                    color="yellow-500"
                  />
                  <ButtonDisplay type="solid" label="Button" color="white" />
                </div>
                <div className="flex flex-col gap-[15px] items-start">
                  <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                    Outlined
                  </p>
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="button-dark"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="button-gray"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="emerald-500"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="blue-500"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="button-purple"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="red-500"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="button-orange"
                  />
                  <ButtonDisplay
                    type="outline"
                    label="Button"
                    color="yellow-500"
                  />
                  <ButtonDisplay type="outline" label="Button" color="white" />
                </div>
                <div className="flex flex-col gap-[15px] items-start">
                  <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                    Ghost
                  </p>
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="button-dark"
                  />
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="button-gray"
                  />
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="emerald-500"
                  />
                  <ButtonDisplay type="ghost" label="Button" color="blue-500" />
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="button-purple"
                  />
                  <ButtonDisplay type="ghost" label="Button" color="red-500" />
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="button-orange"
                  />
                  <ButtonDisplay
                    type="ghost"
                    label="Button"
                    color="yellow-500"
                  />
                  <ButtonDisplay type="ghost" label="Button" color="white" />
                </div>
                <div className="flex flex-col gap-[15px] items-start">
                  <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                    Soft
                  </p>
                  <ButtonDisplay type="soft" label="Button" color="gray-100" />
                  <ButtonDisplay type="soft" label="Button" color="gray-50" />
                  <ButtonDisplay
                    type="soft"
                    label="Button"
                    color="emerald-100"
                  />
                  <ButtonDisplay type="soft" label="Button" color="blue-50" />
                  <ButtonDisplay type="soft" label="Button" color="ebdff9" />
                  <ButtonDisplay type="soft" label="Button" color="red-100" />
                  <ButtonDisplay type="soft" label="Button" color="ffd8cc" />
                  <ButtonDisplay
                    type="soft"
                    label="Button"
                    color="yellow-100"
                  />
                  <ButtonDisplay type="soft" label="Button" color="white/10" />
                </div>
              </div>
              <div className="flex flex-col gap-[30px] items-start self-stretch relative w-full mt-10">
                <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full">
                  <p className="text-lg leading-[22px] tracking-[0.005em] text-black font-medium">
                    Block Buttons
                  </p>
                  <div className="w-full h-px bg-gray-200"></div>
                </div>
                <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full">
                  <button className="flex gap-0 items-start self-stretch relative w-full bg-transparent">
                    <div className="overflow-hidden rounded-md px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-[#5a00cd]">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-white font-medium">
                        Button
                      </p>
                    </div>
                  </button>
                  <button className="flex gap-0 items-start self-stretch relative w-full bg-transparent">
                    <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                        Button
                      </p>
                    </div>
                  </button>
                </div>
              </div>
              <div className="flex flex-col gap-[30px] items-start relative mt-10">
                <div className="flex flex-col gap-2.5 items-start self-stretch relative w-full">
                  <p className="text-lg leading-[22px] tracking-[0.005em] text-black font-medium">
                    Examples
                  </p>
                  <div className="w-full h-px bg-gray-200"></div>
                </div>
                <div className="flex gap-10 items-start self-stretch relative w-full">
                  <div className="flex flex-col gap-[15px] items-start relative">
                    <div className="relative w-full h-[17px] bg-transparent">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                        Trailing Divider
                      </p>
                    </div>
                    <button className="flex gap-0 items-start relative bg-transparent">
                      <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                        <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                          Button
                        </p>
                        <div className="w-px h-full bg-gray-200"></div>
                        <svg
                          width="15"
                          height="16"
                          viewBox="0 0 15 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fillRule="evenodd"
                            clipRule="evenodd"
                            d="M1.54311 4.85561C1.58665 4.81196 1.63838 4.77732 1.69533 4.75369C1.75228 4.73006 1.81333 4.7179 1.87498 4.7179C1.93664 4.7179 1.99769 4.73006 2.05464 4.75369C2.11159 4.77732 2.16332 4.81196 2.20686 4.85561L7.49998 10.1497L12.7931 4.85561C12.8367 4.81203 12.8884 4.77745 12.9454 4.75387C13.0023 4.73028 13.0633 4.71814 13.125 4.71814C13.1866 4.71814 13.2476 4.73028 13.3046 4.75387C13.3615 4.77745 13.4133 4.81203 13.4569 4.85561C13.5004 4.89919 13.535 4.95093 13.5586 5.00787C13.5822 5.06482 13.5943 5.12585 13.5943 5.18748C13.5943 5.24912 13.5822 5.31015 13.5586 5.36709C13.535 5.42404 13.5004 5.47578 13.4569 5.51936L7.83186 11.1444C7.78832 11.188 7.73659 11.2226 7.67964 11.2463C7.62269 11.2699 7.56164 11.2821 7.49998 11.2821C7.43833 11.2821 7.37728 11.2699 7.32033 11.2463C7.26338 11.2226 7.21165 11.188 7.16811 11.1444L1.54311 5.51936C1.49946 5.47582 1.46482 5.42409 1.44119 5.36714C1.41756 5.31019 1.4054 5.24914 1.4054 5.18748C1.4054 5.12583 1.41756 5.06478 1.44119 5.00783C1.46482 4.95088 1.49946 4.89915 1.54311 4.85561V4.85561Z"
                            fill="#1F2937"
                          />
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div className="flex flex-col gap-[15px] items-start relative">
                    <div className="relative w-full h-[17px] bg-transparent">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                        Leading Icon
                      </p>
                    </div>
                    <button className="flex gap-0 items-start relative bg-transparent">
                      <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                        <svg
                          width="15"
                          height="16"
                          viewBox="0 0 15 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M5.625 8C6.37092 8 7.08629 7.70368 7.61374 7.17624C8.14118 6.64879 8.4375 5.93342 8.4375 5.1875C8.4375 4.44158 8.14118 3.72621 7.61374 3.19876C7.08629 2.67132 6.37092 2.375 5.625 2.375C4.87908 2.375 4.16371 2.67132 3.63626 3.19876C3.10882 3.72621 2.8125 4.44158 2.8125 5.1875C2.8125 5.93342 3.10882 6.64879 3.63626 7.17624C4.16371 7.70368 4.87908 8 5.625 8V8ZM7.5 5.1875C7.5 5.68478 7.30246 6.16169 6.95083 6.51333C6.59919 6.86496 6.12228 7.0625 5.625 7.0625C5.12772 7.0625 4.65081 6.86496 4.29917 6.51333C3.94754 6.16169 3.75 5.68478 3.75 5.1875C3.75 4.69022 3.94754 4.21331 4.29917 3.86167C4.65081 3.51004 5.12772 3.3125 5.625 3.3125C6.12228 3.3125 6.59919 3.51004 6.95083 3.86167C7.30246 4.21331 7.5 4.69022 7.5 5.1875V5.1875ZM11.25 12.6875C11.25 13.625 10.3125 13.625 10.3125 13.625H0.9375C0.9375 13.625 0 13.625 0 12.6875C0 11.75 0.9375 8.9375 5.625 8.9375C10.3125 8.9375 11.25 11.75 11.25 12.6875ZM10.3125 12.6838C10.3116 12.4531 10.1681 11.7594 9.5325 11.1237C8.92125 10.5125 7.77094 9.875 5.625 9.875C3.47813 9.875 2.32875 10.5125 1.7175 11.1237C1.08188 11.7594 0.939375 12.4531 0.9375 12.6838H10.3125Z"
                            fill="#1F2937"
                          />
                          <path
                            fillRule="evenodd"
                            clipRule="evenodd"
                            d="M12.6562 5.1875C12.7806 5.1875 12.8998 5.23689 12.9877 5.32479C13.0756 5.4127 13.125 5.53193 13.125 5.65625V7.0625H14.5312C14.6556 7.0625 14.7748 7.11189 14.8627 7.19979C14.9506 7.2877 15 7.40693 15 7.53125C15 7.65557 14.9506 7.7748 14.8627 7.86271C14.7748 7.95061 14.6556 8 14.5312 8H13.125V9.40625C13.125 9.53057 13.0756 9.6498 12.9877 9.73771C12.8998 9.82561 12.7806 9.875 12.6562 9.875C12.5319 9.875 12.4127 9.82561 12.3248 9.73771C12.2369 9.6498 12.1875 9.53057 12.1875 9.40625V8H10.7812C10.6569 8 10.5377 7.95061 10.4498 7.86271C10.3619 7.7748 10.3125 7.65557 10.3125 7.53125C10.3125 7.40693 10.3619 7.2877 10.4498 7.19979C10.5377 7.11189 10.6569 7.0625 10.7812 7.0625H12.1875V5.65625C12.1875 5.53193 12.2369 5.4127 12.3248 5.32479C12.4127 5.23689 12.5319 5.1875 12.6562 5.1875Z"
                            fill="#1F2937"
                          />
                        </svg>
                        <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                          Button
                        </p>
                      </div>
                    </button>
                  </div>
                  <div className="flex flex-col gap-[15px] items-start relative">
                    <div className="relative w-full h-[17px] bg-transparent">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                        Trailing Icon
                      </p>
                    </div>
                    <button className="flex gap-0 items-start relative bg-transparent">
                      <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                        <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                          Button
                        </p>
                        <svg
                          width="15"
                          height="16"
                          viewBox="0 0 15 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <g clipPath="url(#clip0_1733_24076)">
                            <path
                              d="M5.39719 1.50406C5.45001 1.53569 5.49609 1.57742 5.53278 1.62686C5.56947 1.6763 5.59607 1.73249 5.61104 1.79221C5.62602 1.85194 5.62908 1.91402 5.62005 1.97493C5.61103 2.03584 5.59009 2.09437 5.55844 2.14718L3.17156 6.12499H11.8284L9.44062 2.14718C9.37672 2.04051 9.35781 1.91283 9.38805 1.79222C9.41829 1.67161 9.49521 1.56796 9.60187 1.50406C9.70854 1.44016 9.83622 1.42125 9.95683 1.45149C10.0774 1.48173 10.1811 1.55864 10.245 1.66531L12.9216 6.12499H14.0625C14.3111 6.12499 14.5496 6.22377 14.7254 6.39958C14.9012 6.5754 15 6.81385 15 7.06249V7.99999C15 8.24863 14.9012 8.48709 14.7254 8.66291C14.5496 8.83872 14.3111 8.93749 14.0625 8.93749V13.1562C14.0625 13.7778 13.8156 14.374 13.376 14.8135C12.9365 15.2531 12.3404 15.5 11.7188 15.5H3.28125C2.65965 15.5 2.06351 15.2531 1.62397 14.8135C1.18443 14.374 0.9375 13.7778 0.9375 13.1562V8.93749C0.68886 8.93749 0.450403 8.83872 0.274587 8.66291C0.0987721 8.48709 0 8.24863 0 7.99999V7.06249C0 6.81385 0.0987721 6.5754 0.274587 6.39958C0.450403 6.22377 0.68886 6.12499 0.9375 6.12499H2.07844L4.75313 1.66531C4.78476 1.61248 4.82649 1.56641 4.87593 1.52971C4.92537 1.49302 4.98156 1.46643 5.04128 1.45145C5.10101 1.43648 5.16309 1.43342 5.224 1.44244C5.28491 1.45147 5.34344 1.4724 5.39625 1.50406H5.39719ZM1.875 8.93749V13.1562C1.875 13.5292 2.02316 13.8869 2.28688 14.1506C2.5506 14.4143 2.90829 14.5625 3.28125 14.5625H11.7188C12.0917 14.5625 12.4494 14.4143 12.7131 14.1506C12.9768 13.8869 13.125 13.5292 13.125 13.1562V8.93749H1.875ZM0.9375 7.06249V7.99999H14.0625V7.06249H0.9375ZM3.75 9.87499C3.87432 9.87499 3.99355 9.92438 4.08146 10.0123C4.16936 10.1002 4.21875 10.2194 4.21875 10.3437V13.1562C4.21875 13.2806 4.16936 13.3998 4.08146 13.4877C3.99355 13.5756 3.87432 13.625 3.75 13.625C3.62568 13.625 3.50645 13.5756 3.41854 13.4877C3.33064 13.3998 3.28125 13.2806 3.28125 13.1562V10.3437C3.28125 10.2194 3.33064 10.1002 3.41854 10.0123C3.50645 9.92438 3.62568 9.87499 3.75 9.87499ZM5.625 9.87499C5.74932 9.87499 5.86855 9.92438 5.95646 10.0123C6.04436 10.1002 6.09375 10.2194 6.09375 10.3437V13.1562C6.09375 13.2806 6.04436 13.3998 5.95646 13.4877C5.86855 13.5756 5.74932 13.625 5.625 13.625C5.50068 13.625 5.38145 13.5756 5.29354 13.4877C5.20564 13.3998 5.15625 13.2806 5.15625 13.1562V10.3437C5.15625 10.2194 5.20564 10.1002 5.29354 10.0123C5.38145 9.92438 5.50068 9.87499 5.625 9.87499V9.87499ZM7.5 9.87499C7.62432 9.87499 7.74355 9.92438 7.83146 10.0123C7.91936 10.1002 7.96875 10.2194 7.96875 10.3437V13.1562C7.96875 13.2806 7.91936 13.3998 7.83146 13.4877C7.74355 13.5756 7.62432 13.625 7.5 13.625C7.37568 13.625 7.25645 13.5756 7.16854 13.4877C7.08064 13.3998 7.03125 13.2806 7.03125 13.1562V10.3437C7.03125 10.2194 7.08064 10.1002 7.16854 10.0123C7.25645 9.92438 7.37568 9.87499 7.5 9.87499V9.87499ZM9.375 9.87499C9.49932 9.87499 9.61855 9.92438 9.70646 10.0123C9.79436 10.1002 9.84375 10.2194 9.84375 10.3437V13.1562C9.84375 13.2806 9.79436 13.3998 9.70646 13.4877C9.61855 13.5756 9.49932 13.625 9.375 13.625C9.25068 13.625 9.13145 13.5756 9.04354 13.4877C8.95564 13.3998 8.90625 13.2806 8.90625 13.1562V10.3437C8.90625 10.2194 8.95564 10.1002 9.04354 10.0123C9.13145 9.92438 9.25068 9.87499 9.375 9.87499ZM11.25 9.87499C11.3743 9.87499 11.4935 9.92438 11.5815 10.0123C11.6694 10.1002 11.7188 10.2194 11.7188 10.3437V13.1562C11.7188 13.2806 11.6694 13.3998 11.5815 13.4877C11.4935 13.5756 11.3743 13.625 11.25 13.625C11.1257 13.625 11.0065 13.5756 10.9185 13.4877C10.8306 13.3998 10.7812 13.2806 10.7812 13.1562V10.3437C10.7812 10.2194 10.8306 10.1002 10.9185 10.0123C11.0065 9.92438 11.1257 9.87499 11.25 9.87499Z"
                              fill="#1F2937"
                            />
                          </g>
                          <defs>
                            <clipPath id="clip0_1733_24076">
                              <rect
                                width="15"
                                height="15"
                                fill="white"
                                transform="translate(0 0.5)"
                              />
                            </clipPath>
                          </defs>
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div className="flex flex-col gap-[15px] items-start relative">
                    <div className="relative w-full h-[17px] bg-transparent">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                        Leading Avatar + Trailing Icon
                      </p>
                    </div>
                    <div className="flex gap-5 items-start relative">
                      <button className="flex gap-0 items-start relative bg-transparent">
                        <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                          <svg
                            width="18"
                            height="18"
                            viewBox="0 0 18 18"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <g clipPath="url(#clip0_1733_22747)">
                              <path
                                d="M17.4881 7.37779C17.5931 7.98187 17.6454 8.59392 17.6445 9.20704C17.6445 11.9453 16.6658 14.2605 14.9625 15.8277H14.9648C13.4753 17.2035 11.4278 18 9 18C6.61305 18 4.32387 17.0518 2.63604 15.364C0.948212 13.6762 0 11.387 0 9.00004C0 6.6131 0.948212 4.32391 2.63604 2.63608C4.32387 0.948256 6.61305 4.4556e-05 9 4.4556e-05C11.2342 -0.0261211 13.3918 0.813231 15.021 2.34229L12.4515 4.91179C11.5227 4.02639 10.2831 3.54153 9 3.56179C6.65213 3.56179 4.6575 5.14579 3.9465 7.27879C3.56952 8.39649 3.56952 9.60698 3.9465 10.7247H3.94988C4.66425 12.8543 6.6555 14.4383 9.00338 14.4383C10.2161 14.4383 11.2579 14.1278 12.0656 13.5788H12.0623C12.5313 13.2681 12.9325 12.8655 13.2416 12.3955C13.5508 11.9255 13.7616 11.3976 13.8611 10.8439H9V7.37892H17.4881V7.37779Z"
                                fill="#1F2937"
                              />
                            </g>
                            <defs>
                              <clipPath id="clip0_1733_22747">
                                <rect
                                  width="18"
                                  height="18"
                                  rx="9"
                                  fill="white"
                                />
                              </clipPath>
                            </defs>
                          </svg>
                          <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                            Button
                          </p>
                          <svg
                            width="15"
                            height="16"
                            viewBox="0 0 15 16"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M4.35561 2.04311C4.39915 1.99946 4.45088 1.96482 4.50783 1.94119C4.56478 1.91756 4.62583 1.9054 4.68748 1.9054C4.74914 1.9054 4.81019 1.91756 4.86714 1.94119C4.92409 1.96482 4.97582 1.99946 5.01936 2.04311L10.6444 7.66811C10.688 7.71165 10.7226 7.76338 10.7463 7.82033C10.7699 7.87728 10.7821 7.93833 10.7821 7.99998C10.7821 8.06164 10.7699 8.12269 10.7463 8.17964C10.7226 8.23659 10.688 8.28832 10.6444 8.33186L5.01936 13.9569C4.93134 14.0449 4.81196 14.0943 4.68748 14.0943C4.56301 14.0943 4.44363 14.0449 4.35561 13.9569C4.26759 13.8688 4.21814 13.7495 4.21814 13.625C4.21814 13.5005 4.26759 13.3811 4.35561 13.2931L9.64967 8.99998L4.35561 3.70686C4.31196 3.66332 4.27732 3.61159 4.25369 3.55464C4.23006 3.49769 4.2179 3.43664 4.2179 3.37498C4.2179 3.31333 4.23006 3.25228 4.25369 3.19533C4.27732 3.13838 4.31196 3.08665 4.35561 3.04311V3.04311Z"
                              fill="#1F2937"
                            />
                          </svg>
                        </div>
                      </button>
                      <button className="flex gap-0 items-start relative bg-transparent">
                        <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                          <div className="relative w-[18px] h-[18px] bg-transparent">
                            <img
                              src="https://picsum.photos/id/58/18/18"
                              className="w-[18px] h-[18px] bg-[url('https://picsum.photos/id/2/18/18')]"
                            />
                          </div>
                          <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                            Button
                          </p>
                          <svg
                            width="15"
                            height="16"
                            viewBox="0 0 15 16"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M4.35561 2.04311C4.39915 1.99946 4.45088 1.96482 4.50783 1.94119C4.56478 1.91756 4.62583 1.9054 4.68748 1.9054C4.74914 1.9054 4.81019 1.91756 4.86714 1.94119C4.92409 1.96482 4.97582 1.99946 5.01936 2.04311L10.6444 7.66811C10.688 7.71165 10.7226 7.76338 10.7463 7.82033C10.7699 7.87728 10.7821 7.93833 10.7821 7.99998C10.7821 8.06164 10.7699 8.12269 10.7463 8.17964C10.7226 8.23659 10.688 8.28832 10.6444 8.33186L5.01936 13.9569C4.93134 14.0449 4.81196 14.0943 4.68748 14.0943C4.56301 14.0943 4.44363 14.0449 4.35561 13.9569C4.26759 13.8688 4.21814 13.7495 4.21814 13.625C4.21814 13.5005 4.26759 13.3811 4.35561 13.2931L9.64967 8.99998L4.35561 3.70686C4.31196 3.66332 4.27732 3.61159 4.25369 3.55464C4.23006 3.49769 4.2179 3.43664 4.2179 3.37498C4.2179 3.31333 4.23006 3.25228 4.25369 3.19533C4.27732 3.13838 4.31196 3.08665 4.35561 3.04311V3.04311Z"
                              fill="#1F2937"
                            />
                          </svg>
                        </div>
                      </button>
                    </div>
                  </div>
                  <div className="flex flex-col gap-[15px] items-start relative">
                    <div className="relative w-full h-[17px] bg-transparent">
                      <p className="text-[15px] leading-[18px] tracking-[0.005em] text-slate-600 font-medium">
                        Badge
                      </p>
                    </div>
                    <div className="flex gap-5 items-start relative">
                      <button className="flex gap-0 items-start relative bg-transparent">
                        <div className="overflow-hidden shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-gray-200 px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-white">
                          <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-[#09041a] font-medium">
                            Button
                          </p>
                          <div className="flex gap-0 items-start relative w-5 h-5 bg-transparent">
                            <div className="shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-[20px] border border-[#e1e0e5] px-1 py-0.5 flex gap-px justify-center items-center flex-1 self-stretch relative w-full h-full bg-white">
                              <div className="px-0.5 flex gap-[7px] items-center relative">
                                <div className="pt-0 pb-px flex gap-0 items-start relative">
                                  <small className="text-[10px] leading-4 tracking-[0.005em] text-center text-[#110733] font-bold">
                                    5
                                  </small>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </button>
                      <button className="flex gap-0 items-start relative bg-transparent">
                        <div className="overflow-hidden rounded-md px-5 py-[14px] flex gap-2.5 justify-center items-center relative bg-[#5a00cd]">
                          <p className="text-[15px] leading-[18px] tracking-[0.005em] text-center text-white font-medium">
                            Button
                          </p>
                          <div className="flex gap-0 items-start relative bg-transparent">
                            <div className="shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] rounded-md border border-[#e1e0e5] px-1 py-0.5 flex gap-px items-center relative bg-white">
                              <div className="px-0.5 flex gap-[7px] items-center relative">
                                <div className="pt-0 pb-px flex gap-0 items-start relative">
                                  <small className="text-[10px] leading-4 tracking-[0.005em] text-[#110733] font-bold">
                                    5
                                  </small>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        )}
      </div>
    </div>
  );
};

export default DesignPage;
