name: Sync Build Files to S3 integration

on:
  push:
    branches:
      - integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.3'

      - name: Set up local environment variables
        run: |
          touch .env.local
          echo VITE_API_HOST=${{vars.API_HOST_INT}} >> .env.local
          echo VITE_API_HOST_PUBLIC=${{vars.API_HOST_PUBLIC_INT}} >> .env.local
          echo VITE_SYSTEM_TYPE=${{vars.SYSTEM_TYPE_ADMIN}} >> .env.local
          echo VITE_SOCKET_URL=${{vars.SOCKET_URL_INT}} >> .env.local
          echo VITE_GITHUB_CLIENT_ID=${{vars.CLIENT_ID_INT}} >> .env.local
          echo VITE_CRYPTO_KEY=${{secrets.CRYPTO_KEY_INT}} >> .env.local
          echo VITE_SURVEY_FORM_URL=${{vars.SURVEY_FORM_URL_INT}} >> .env.local

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Sync files to S3
        run: |
          aws s3 sync ./dist s3://${{vars.AWS_S3_BUCKET_INT}} --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up system type local environment variable for public
        run: |
          echo VITE_SYSTEM_TYPE=${{vars.SYSTEM_TYPE_PUBLIC}} >> .env.local
          echo VITE_ADMIN_HOST=${{vars.ADMIN_HOST_INT}} >> .env.local

      - name: Build project for public
        run: npm run build

      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add public IP to EC2 security group
        run: |
          PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
          aws ec2 authorize-security-group-ingress --group-id ${{ vars.AWS_SECURITY_GROUP_ID_INT }} --protocol tcp --port 22 --cidr $PUBLIC_IP/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Copy build files to EC2 instance
        run: |
          touch id_rsa
          echo "${{ secrets.AWS_EC2_KEY }}" > id_rsa
          chmod 600 id_rsa
          scp -o StrictHostKeyChecking=no -i id_rsa -r ./dist/* ${{ vars.AWS_EC2_USER }}@${{ vars.AWS_EC2_INSTANCE_IP_INT }}:/home/nino/dev/productfeedback-skywalk/dist/
        env:
          EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
          EC2_INSTANCE_IP: ${{ vars.AWS_EC2_INSTANCE_IP_INT }}

      - name: Remove public IP from EC2 security group
        run: |
          PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
          aws ec2 revoke-security-group-ingress --group-id ${{ vars.AWS_SECURITY_GROUP_ID_INT }} --protocol tcp --port 22 --cidr $PUBLIC_IP/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
