import React from 'react';

interface FontDisplayProps {
  fontFamily: string;
  fontSize: string;
  fontWeight: string;
  sampleText: string;
}

// Ensure these classes are generated by Tailwind
// Font Sizes
// text-xs text-sm text-base text-lg text-xl text-2xl text-3xl text-4xl text-5xl text-6xl text-7xl text-8xl text-9xl

// Font Weights
// font-normal font-medium font-bold

const FontDisplay: React.FC<FontDisplayProps> = ({ fontFamily, fontSize, fontWeight, sampleText }) => {
  return (
    <div className="mb-4">
      <p className={`font-${fontFamily} text-${fontSize} font-${fontWeight}`}>
        {sampleText}
      </p>
      <div className="text-sm text-gray-500">
        {`Font: ${fontFamily}, Size: ${fontSize}, Weight: ${fontWeight}`}
      </div>
    </div>
  );
};

export default FontDisplay; 